class StorageKey {

  static ENABLE() { return 'REDSTOP_ENABLE'; }
  static OPTION_TAB() { return 'REDSTOP_OPTION_TAB'; }
  static LAST_DATA_DOWNLOAD_TIME() { return 'REDSTOP_LAST_DATA_DOWNLOAD_TIME'; }

  // function
  static FUNCTION_WIKI() { return 'REDSTOP_FUNCTION_WIKI'; }
  static FUNCTION_FACEBOOK() { return 'REDSTOP_FUNCTION_FACEBOOK'; }
  static FUNCTION_IG() { return 'REDSTOP_FUNCTION_IG'; }
  static FUNCTION_TWITTER() { return 'REDSTOP_FUNCTION_TWITTER'; }
  static FUNCTION_OPENRICE() { return 'REDSTOP_FUNCTION_OPENRICE'; }
  static FUNCTION_IOS() { return 'REDSTOP_FUNCTION_IOS'; }
  static FUNCTION_ANDROID() { return 'REDSTOP_FUNCTION_ANDROID'; }
  static FUNCTION_STEAM() { return 'REDSTOP_FUNCTION_STEAM'; }
  static FUNCTION_PS() { return 'REDSTOP_FUNCTION_PS'; }
  static FUNCTION_XBOX() { return 'REDSTOP_FUNCTION_XBOX'; }
  static FUNCTION_SWITCH() { return 'REDSTOP_FUNCTION_SWITCH'; }
  static FUNCTION_CHECK_DOMAIN_CN() { return 'REDSTOP_FUNCTION_CHECK_DOMAIN_CN'; }
  static FUNCTION_CHECK_CHINA_ICP() { return 'REDSTOP_FUNCTION_CHECK_CHINA_ICP'; }

  // appearance
  static APPEARANCE_MENU_DARK_MODE() { return 'REDSTOP_APPEARANCE_MENU_DARK_MODE'; }
  static APPEARANCE_NOTIFICATION_DARK_MODE() { return 'REDSTOP_APPEARANCE_NOTIFICATION_DARK_MODE'; }
  static APPEARANCE_NOTIFICATION_POSITION() { return 'REDSTOP_APPEARANCE_NOTIFICATION_POSITION'; }
  static APPEARANCE_AUTO_HIDE() { return 'REDSTOP_APPEARANCE_AUTO_HIDE'; }
  static APPEARANCE_AUTO_HIDE_TIME() { return 'REDSTOP_APPEARANCE_AUTO_HIDE_TIME'; }

  // except site
  static EXCEPT_SITE_WEBSITE() { return 'REDSTOP_EXCEPT_SITE_WEBSITE'; }
  static EXCEPT_SITE_WIKI() { return 'REDSTOP_EXCEPT_SITE_WIKI'; }
  static EXCEPT_SITE_FACEBOOK() { return 'REDSTOP_EXCEPT_SITE_FACEBOOK'; }
  static EXCEPT_SITE_IG() { return 'REDSTOP_EXCEPT_SITE_IG'; }
  static EXCEPT_SITE_TWITTER() { return 'REDSTOP_EXCEPT_SITE_TWITTER'; }
  static EXCEPT_SITE_OPENRICE() { return 'REDSTOP_EXCEPT_SITE_OPENRICE'; }
  static EXCEPT_SITE_IOS_STORE() { return 'REDSTOP_EXCEPT_SITE_IOS_STORE'; }
  static EXCEPT_SITE_IOS_APP() { return 'REDSTOP_EXCEPT_SITE_IOS_APP'; }
  static EXCEPT_SITE_ANDROID_STORE() { return 'REDSTOP_EXCEPT_SITE_ANDROID_STORE'; }
  static EXCEPT_SITE_ANDROID_PACKAGE() { return 'REDSTOP_EXCEPT_SITE_ANDROID_PACKAGE'; }
  static EXCEPT_SITE_STEAM_STORE() { return 'REDSTOP_EXCEPT_SITE_STEAM_STORE'; }
  static EXCEPT_SITE_STEAM_APP() { return 'REDSTOP_EXCEPT_SITE_STEAM_APP'; }
  static EXCEPT_SITE_PS_APP() { return 'REDSTOP_EXCEPT_SITE_PS_APP'; }
  static EXCEPT_SITE_XBOX_APP() { return 'REDSTOP_EXCEPT_SITE_XBOX_APP'; }
  static EXCEPT_SITE_SWITCH_APP() { return 'REDSTOP_EXCEPT_SITE_SWITCH_APP'; }

}
